---
- fail:
    msg: You may only define one of 'mounts_cryptdisks.uuid' or 'mounts_cryptdisks.net_path'
  when: mounts_cryptdisks.uuid is defined and mounts_cryptdisks.net_path is defined

- name: Create folder for the cryptdisks mount point
  become: true
  file:
    state: directory
    owner: root
    group: root
    mode: '0700'
    path: "{{ mounts_cryptdisks.mount_point }}"

- name: "Configure `CRYPTDISKS_MOUNT` in '{{ mounts_cryptdisks_path }}'"
  become: true
  lineinfile:
    path: "{{ mounts_cryptdisks_path }}"
    regexp: '^CRYPTDISKS_MOUNT=.+'
    line: "CRYPTDISKS_MOUNT=\"{{ mounts_cryptdisks.mount_point | default('') }}\""

- name: Push out the credentials file
  become: true
  template:
    src: smbcredentials.j2
    dest: "{{ mounts_cryptdisks.net_credentials.path }}"
    owner: root
    group: root
    mode: '0600'
  when: mounts_cryptdisks.net_credentials.path is defined
